version: '3'

services:
  flask:
    build: ./flask
    environment:
      - SERVER_URL=localhost
      - MONGO_CONFIG=mongodb://mongoadmin:yXxadGUpyv7dnrs4@mongo:27017/
      - OPEN_REGISTER=1
      - SECRET_KEY=test
    volumes:
      - ./app:/app
      - ./flask/uwsgi.ini:/etc/uwsgi/uwsgi.ini
  nginx:
    image: nginx:1.12.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
      - ./app:/usr/share/nginx/app
    depends_on:
      - flask
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=yXxadGUpyv7dnrs4
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ~/data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=yXxadGUpyv7dnrs4
      - ME_CONFIG_BASICAUTH_USERNAME=webadmin
      - ME_CONFIG_BASICAUTH_PASSWORD=6eKJm6HNLx5KpdxM